[serilog]

using = [
    "Serilog.Sinks.Console",
    "Serilog.Sinks.File"
]
enrich = ["FromLogContext"]

[serilog.minimumlevel]
default = "Information"
override = { Microsoft = "Warning", System = "Warning" }

[[serilog.writeto]]
name = "Console"

[serilog.writeto.args]
outputtemplate = "{UniqueId} | {LogEvent} | {Message}{NewLine}{Exception}"

[[serilog.writeto]]
name = "File"

[serilog.writeto.args]
path = "%USERPROFILE%\\.ring\\logs\\ring.log"
rollinginterval = "Hour"
outputtemplate = "[{Timestamp:HH:mm:ss} {Level:u3}] | {Phase} | {UniqueId} | {Message}{NewLine}{Exception}"
hooks = "Queil.Ring.DotNet.Cli.Logging.NewLogFileNotifier::Current, ATech.Ring.DotNet.Cli"
